[package]
name = "forge-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
forge-proto = { workspace = true }
forge-common = { workspace = true }
forge-shuffle = { workspace = true }
arrow = { workspace = true }
datafusion = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
