variable "name" {
  type        = string
  default     = "lakeforge"
  description = "Prefix for every resource (cluster, bucket, database)."
}
variable "region" {
  type    = string
  default = "us-east-1"
}
variable "vpc_cidr" {
  type    = string
  default = "10.42.0.0/16"
}
variable "kubernetes_version" {
  type    = string
  default = "1.30"
}
variable "control_plane_instance_type" {
  type    = string
  default = "m6i.large"
}
variable "compute_instance_type" {
  type    = string
  default = "m6i.2xlarge"
}
variable "compute_min_nodes" {
  type    = number
  default = 1
}
variable "compute_max_nodes" {
  type    = number
  default = 10
}
variable "db_instance_class" {
  type    = string
  default = "db.t4g.medium"
}
variable "db_multi_az" {
  type    = bool
  default = false
}
variable "force_destroy_storage" {
  type        = bool
  default     = false
  description = "Allow `terraform destroy` to delete the workspace bucket and database without snapshots (dev only)."
}
variable "namespace" {
  type    = string
  default = "lakeforge"
}
variable "api_image" {
  type    = string
  default = "ghcr.io/andyh-viv/lakeforge-api"
}
variable "forge_image" {
  type    = string
  default = "ghcr.io/andyh-viv/lakeforge-forge"
}
variable "image_tag" {
  type    = string
  default = "latest"
}
variable "admin_user" {
  type    = string
  default = "admin@lakeforge.local"
}
variable "admin_password" {
  type        = string
  default     = ""
  sensitive   = true
  description = "Initial admin password; generated by the chart when empty."
}
variable "public_url" {
  type        = string
  default     = ""
  description = "Public URL (e.g. https://lakeforge.example.com). Defaults to the load balancer address."
}
variable "extra_helm_values" {
  type    = any
  default = {}
}
variable "tags" {
  type    = map(string)
  default = {}
}
